### ISSUE TITLE
ORU_R01 missing obx fields

### ISSUE THREAD

**Issue by ryoung29** [crs4/hl7apy#78]
First of all, thank you for all the hard work on this library. It is by far my favorite HL7 library for Python.

According to [this specification](http://dhhs.ne.gov/epi%20docs/HL7-2.5.1-Guide.pdf), obx should have up to 25 fields, but the implementation only has 22.

I will be sending a pull request to add the 3 extra fields.

**Comment by asulis** [comment]
Dear RYoung, 

first of all thank you, we are pleased to know that you appreciate our work. Thank you also for your good catch: the library effectively misses OBX 23, 24 and 25 fields support for the OBX segment in the 2.5.1 version. However, concerning your PR, notice that HL7 does not have an official 2.5.2 release, so as the library must be kept aligned with official HL7 releases, what we have to do to fix this issue is to do that in the 2.5.1 version. The only thing you should do here is to fix 2.5.1's segments.py and fields.py.
Could you abort your PR and insert a new one for that ?

Best regards, 
Alessandro

**Comment by ryoung29** [comment]
Sure thing. I almost asked if I should take that approach before I submitted a PR. I'll update it.

**Comment by svituz** [comment]
closed in #919d81b36d0fdf53d69fd7e842c70094e34fde47
